# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(843, 381)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(32233, 505))
        self.frame.setStyleSheet("QFrame { \n"
"    color: rgb(9, 91, 255);\n"
"    background-color: rgb(9, 24, 49);\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(9, 91, 255);\n"
"    border-radius: 5px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 52, 237);\n"
"    border-radius: 8px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"\n"
"QTextEdit{\n"
"    border-style: solid;        \n"
"    border-width: 3px;      \n"
"    border-radius: 5px;\n"
"    border-color: rgb(202, 205, 209);\n"
"    color: rgb(87, 95, 107);\n"
"}\n"
"\n"
"QRadioButton{\n"
"    color: rgb(87, 95, 107);\n"
"}\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setMinimumSize(QtCore.QSize(401, 367))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout.setObjectName("gridLayout")
        self.btnReset = QtWidgets.QPushButton(self.frame_2)
        self.btnReset.setObjectName("btnReset")
        self.gridLayout.addWidget(self.btnReset, 1, 0, 1, 2)
        self.btnRun = QtWidgets.QPushButton(self.frame_2)
        self.btnRun.setObjectName("btnRun")
        self.gridLayout.addWidget(self.btnRun, 2, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 5, 0, 1, 1)
        self.btnSellerEmail = QtWidgets.QPushButton(self.frame_2)
        self.btnSellerEmail.setObjectName("btnSellerEmail")
        self.gridLayout.addWidget(self.btnSellerEmail, 4, 1, 1, 1)
        self.btnCheck = QtWidgets.QPushButton(self.frame_2)
        self.btnCheck.setObjectName("btnCheck")
        self.gridLayout.addWidget(self.btnCheck, 6, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 7, 0, 1, 1)
        self.btnBuyerEmail = QtWidgets.QPushButton(self.frame_2)
        self.btnBuyerEmail.setMaximumSize(QtCore.QSize(181, 16777215))
        self.btnBuyerEmail.setObjectName("btnBuyerEmail")
        self.gridLayout.addWidget(self.btnBuyerEmail, 4, 0, 1, 1)
        self.inpCheck = QtWidgets.QTextEdit(self.frame_2)
        self.inpCheck.setMaximumSize(QtCore.QSize(181, 28))
        self.inpCheck.setObjectName("inpCheck")
        self.gridLayout.addWidget(self.inpCheck, 6, 0, 1, 1)
        self.inpTurnedIn = QtWidgets.QTextEdit(self.frame_2)
        self.inpTurnedIn.setMaximumSize(QtCore.QSize(181, 28))
        self.inpTurnedIn.setObjectName("inpTurnedIn")
        self.gridLayout.addWidget(self.inpTurnedIn, 8, 0, 1, 1)
        self.btnTurnedIn = QtWidgets.QPushButton(self.frame_2)
        self.btnTurnedIn.setObjectName("btnTurnedIn")
        self.gridLayout.addWidget(self.btnTurnedIn, 8, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 9, 0, 1, 1)
        self.horizontalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignTop)
        self.text_frame = QtWidgets.QFrame(self.frame)
        self.text_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.text_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.text_frame.setObjectName("text_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.text_frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dispInfo = QtWidgets.QTextBrowser(self.text_frame)
        self.dispInfo.setObjectName("dispInfo")
        self.verticalLayout_2.addWidget(self.dispInfo)
        self.dispTerminal = QtWidgets.QTextBrowser(self.text_frame)
        self.dispTerminal.setMinimumSize(QtCore.QSize(0, 130))
        self.dispTerminal.setMaximumSize(QtCore.QSize(16777215, 130))
        self.dispTerminal.setStyleSheet("color: rgb(0, 171, 0);")
        self.dispTerminal.setObjectName("dispTerminal")
        self.verticalLayout_2.addWidget(self.dispTerminal)
        self.horizontalLayout.addWidget(self.text_frame)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnReset.setText(_translate("MainWindow", "Reset Data "))
        self.btnRun.setText(_translate("MainWindow", "Connect users"))
        self.btnSellerEmail.setText(_translate("MainWindow", "Email Sellers"))
        self.btnCheck.setText(_translate("MainWindow", "Check "))
        self.btnBuyerEmail.setText(_translate("MainWindow", "Email Buyers"))
        self.inpCheck.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.btnTurnedIn.setText(_translate("MainWindow", "Turned In"))
        self.dispInfo.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Info</p></body></html>"))
        self.dispTerminal.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Terminal</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
